steps:
  # Step 1: Install AWS CLI
  - name: gcr.io/cloud-builders/curl
    args:
      [
        "-LO",
        "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip",
      ]
  - name: ubuntu
    entrypoint: bash
    args:
      - "-c"
      - |
        echo "Installing AWS CLI..."
        apt-get update && apt-get install -y unzip
        unzip awscli-exe-linux-x86_64.zip
        ./aws/install
        aws --version
  # Step 2: Configure AWS CLI with provided credentials
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - "-c"
      - |
        echo "Configuring AWS CLI..."
        aws configure set aws_access_key_id "${_AWS_ACCESS_KEY_ID}"
        aws configure set aws_secret_access_key "${_AWS_SECRET_ACCESS_KEY}"
        aws configure set default.region "${_AWS_DEFAULT_REGION}"
  # Step 3: Access AWS Secrets Manager
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - "-c"
      - |
        echo "Accessing AWS Secrets Manager..."
        # Use pre-defined substitutions for credentials
        SECRET_VALUE=$(aws secretsmanager get-secret-value --secret-id test2 --query 'SecretString' --output text)
        echo "Secret Value Retrieved: $SECRET_VALUE"
# Specify the logs bucket (Optional: remove if using only Cloud Logging)
logsBucket: "gs://onesto-log-bucket"
# Define substitutions
substitutions:
  _AWS_ACCESS_KEY_ID: "AKIA3M7ACZ6TY64Z2MDL"
  _AWS_SECRET_ACCESS_KEY: "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"
  _AWS_DEFAULT_REGION: "ap-southeast-2"
