steps:
  # Step 1: Install AWS CLI
  - name: gcr.io/cloud-builders/curl
    args:
      [
        "-LO",
        "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip",
      ]
  - name: ubuntu
    entrypoint: bash
    args:
      - "-c"
      - |
        echo "Installing AWS CLI..."
        apt-get update && apt-get install -y unzip
        unzip awscli-exe-linux-x86_64.zip
        ./aws/install
        aws --version

  # Step 2: Configure AWS CLI with provided credentials
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    env:
      - "AWS_ACCESS_KEY_ID=AKIA3M7ACZ6TY64Z2MDL"
      - "AWS_SECRET_ACCESS_KEY=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"
      - "AWS_DEFAULT_REGION=ap-southeast-2"
    args:
      - "-c"
      - |
        echo "Configuring AWS CLI..."
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        aws configure set default.region $AWS_DEFAULT_REGION

  # Step 3: Access AWS Secrets Manager
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - "-c"
      - |
        echo "Accessing AWS Secrets Manager..."
        SECRET_VALUE=$(aws secretsmanager get-secret-value --secret-id test2 --query 'SecretString' --output text)
        echo "Secret Value Retrieved: $SECRET_VALUE"

artifacts:
  objects:
    location: "gs://yusufk-test/"
    paths:
      - "imagedefinitions.json"

