apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
  annotations: {}
  labels: {}
description: dev
gke:
  cluster: projects/kubernets-project-440302/locations/us-central1-a/clusters/onesto-dev

